### ISSUE TITLE
Grabación de 2hrs no se ha descargado

### ISSUE THREAD

**Issue by Millka3** [pi-ra/beesy-issue-tracker#20]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Realicé una grabación de Google Meet de 2 horas pero no se ha descargado el archivo, solo visualizo en mis descargas las grabaciones previas que hice como pruebas (las cuales tienen corta duración, ejm: 1 minuto) 
Adjunto captura de pantalla del tiempo que ya llevaba la grabación de Meet:
![WhatsApp Image 2023-08-18 at 16 03 19](https://github.com/pi-ra/beesy-issue-tracker/assets/142633706/cbcd6ff1-d673-4c28-b4c6-0372f904ce40)

### Steps To Reproduce

1.Empezar a grabar con la opción Recorded (una reunión de 2 horas)
2.Pulse Stop para detener la grabación pero no me figuró que se estaba descargando el archivo 
3.Ingrese a las Descargas de mi PC pero no me figuró ese archivo

### Environment details

```Markdown
- OS (Windows / Linux / macOS):Windows
- Browser (Chrome / MS Edge):Chrome
- Media Player (VLC):
```

**Comment by piyu-sh** [comment]
Hey @Millka3, if it was a 2-hour long meeting, it would have been a huge file. In that case when you stop press, it would take a few minutes for the download to get started. 

Did you close the meeting tab or the recording tab(the special pinned tab which Beesy creates) by yourself before the download started? If you did close them manually, that might have stopped the download from starting otherwise it would start downloading after a few minutes.

**Comment by piyu-sh** [comment]
Hey @Millka3, we recently launched v0.0.13 of [Beesy](https://chromewebstore.google.com/detail/beesy-record-google-meets/eabicnldgjknbifdgmnieblkbnggfnde/reviews) with persistent recordings, which means even if your download didn't start for some reason or your browser/system crashed, we still save the recording to the user filesystem.

Here's a quick video on how it works: [video link](https://github.com/pi-ra/beesy-issue-tracker/blob/main/RELEASES.md#v0013--latest--mar-19-2024)

Please give it a try and let us know if it helps !
