### ISSUE TITLE
Auto Recording or Prompt Recording

### ISSUE THREAD

**Issue by ferret-guy** [pi-ra/beesy-issue-tracker#23]
### Is there an existing request for this?

- [X] I have searched the existing issues

### Feature description

Add an option to auto record all meetings I join, or at least a pop up asking "do you want to record?" so I don't forget.

**Comment by rahul-kurup** [comment]
Auto-recording all meetings is not possible as of now, because of some rules and constraints put up by browser APIs on automated extension usage.
But we can definitely look into showing a notification along the lines of "Meet session is in-progress. You may start the recording now". So that the user remembers to do so.

**Comment by rahul-kurup** [comment]
this is now live with v0.0.12 ([See](https://mobius-gitlab.bt.com/platform/tribe/omni-channel-sales/ee-mobile/ee-mobile-api-service/-/merge_requests/31))

**Comment by piyu-sh** [comment]
@ferret-guy ^^
