### ISSUE TITLE
Record button is still disabled on google meet page

### ISSUE THREAD

**Issue by pil0t** [pi-ra/beesy-issue-tracker#27]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Record controls _sometimes_ not enabled on Google Meet page

### Steps To Reproduce

1. Join google meeting
2. Sometimes recording button still disabled (sometimes not)

### Environment including version

```Markdown
- Beesy: 0.0.11
- OS: Win11
- Browser: 120.0.6099.110 
- Media Player: NA
```

### Attachments

![image](https://github.com/pi-ra/beesy-issue-tracker/assets/820134/f2f61ef5-0a56-41e6-8510-f8850f47a595)

**Comment by piyu-sh** [comment]
Hey @pil0t , thanks for raising this.
Have a few questions:
- do the controls remain disabled even after a few seconds, or they get enabled after a few seconds of joining a meet ?
- when this happens, do you remember if the last google meet tab crashed or the browser crashed ? because if the tab or browser crashed this might happen.
- when the controls were disabled, how did you got them to work ?

**Comment by pil0t** [comment]
> do the controls remain disabled even after a few seconds, or they get enabled after a few seconds of joining a meet ?
Sometimes they become enabled, but not now, it's already about ~20 mins, and controls still disabled.

> when this happens, do you remember if the last google meet tab crashed or the browser crashed ? because if the tab or browser crashed this might happen.
Nothing special happened, closed normally. Actually, I just restarted browser and joined meeting again, and it still disabled.

> when the controls were disabled, how did you got them to work ?
Right now still blocked, and I can't use it, unfortunately.

**Comment by piyu-sh** [comment]
Ahh sorry that you're not able to use it @pil0t .

But to enable the controls again, can you try this:
- go to extension page chrome://extensions, and disable/enable the beesy extension and then refresh the google meeting page
- if the above still doesn't work, reinstall the extension, that would definitely reset the state

I know this isn't the best solution, but not really sure how we'll fix this because this is happening only sometimes, so there are no reproducible steps, but we'll see if we can figure out a pattern.

**Comment by pil0t** [comment]
Any logs I can collect to add possibility to debug/reproduce steps?

**Comment by piyu-sh** [comment]
Hey, thanks but we don't have very good logging at this point, just not finding time due to work. 
But will reach out if we need any help.

Also were you able to use the extension after that ?

**Comment by rahul-kurup** [comment]
@pil0t are you still facing this issue?
