### ISSUE TITLE
pc crashed

### ISSUE THREAD

**Issue by icc2icc** [pi-ra/beesy-issue-tracker#28]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I recorded a 1.5 H meeting, & when I pressed stop my pc froze,
it stayed like this for 15 minutes until I restarted the pc
I lost that meeting recording

### Steps To Reproduce

create a LONG recording

### Environment including version

```Markdown
- Beesy: 
- OS:win 10
- Browser:crome
```

**Comment by piyu-sh** [comment]
Hey @icc2icc, so currently recordings are kept in browser memory when a recording is going on and when you stop recording, it is downloaded from memory to user file system.
Currently, there is no way to retrieve a recording if it was not downloaded because it is wiped off memory, but we're exploring ways around this [here](https://github.com/pi-ra/beesy-issue-tracker/issues/25).

**Comment by piyu-sh** [comment]
Hey @icc2icc, we recently launched v0.0.13 of [Beesy](https://chromewebstore.google.com/detail/beesy-record-google-meets/eabicnldgjknbifdgmnieblkbnggfnde/reviews) with persistent recordings, which means even if your download didn't start for some reason or your browser/system crashed, we still save the recording to the user filesystem.

Here's a quick video on how it works: [video link](https://github.com/pi-ra/beesy-issue-tracker/blob/main/RELEASES.md#v0013--latest--mar-19-2024)

Please give it a try and let us know if it helps !
