### ISSUE TITLE
Join a Google Meet to enable recording

### ISSUE THREAD

**Issue by beshoo** [pi-ra/beesy-issue-tracker#29]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I have two Google accounts on my PC.
I tested the plugin using my personal account and it worked perfectly fine. 

However, when I switched to my work account, installed the plugin, and opened Google Meet, my coworkers were present. 

But when I tried to use the plugin to start recording, There was a  message saying "Join a Google Meet to enable recording". 

I'm already in the meeting, so I don't know what else I need to do. 
![image](https://github.com/pi-ra/beesy-issue-tracker/assets/4635115/8681970b-1790-4a87-bccf-ecdbebf77564)

**Can you help me figure out what's going on?**

**Please add the option to automatically start recording and save recordings to a selected location once we close the Google meet!**

### Steps To Reproduce

1. Install the plugin using your work Google account.
2. Open Google Meet 
3. Try to use the plugin to start recording.
4. You will see the message "Join a Google Meet to enable recording," even though you are already in the meeting, then you have encountered the issue.

### Environment including version

```Markdown
- Beesy: 0.0.11

- OS:Windows
- Browser: Chrome
- Media Player: Chrome
```

**Comment by piyu-sh** [comment]
Sorry for such a late reply, have been busy lately.
Has this still been happening, because the recording controls should be enabled as soon as you join a google meet? Maybe it was a one-time issue, but just want to confirm so we can ask for more details.

Also, automatically recording when you join a google meet might not be possible with our current approach because of the limitations of the google apis we use.
But we're working on showing a notification to the user when they join a google meet, so you're reminded to start recording when you join a meet, hope that helps.

**Comment by piyu-sh** [comment]
@beshoo Sorry for such a late reply, have been busy lately.
Has this still been happening, because the recording controls should be enabled as soon as you join a google meet? Maybe it was a one-time issue, but just want to confirm so we can ask for more details.

Also, automatically recording when you join a google meet might not be possible with our current approach because of the limitations of the google apis we use.
But we're working on showing a notification to the user when they join a google meet, so you're reminded to start recording when you join a meet, hope that helps.

**Comment by beshoo** [comment]
Yes it still happens.

Regard

**Comment by piyu-sh** [comment]
@beshoo Could you please create a quick recording and share here ? 
Also please close down any other chrome windows and close any meet tabs that might be open before opening a new meet tab and then start the meeting.

**Comment by piyu-sh** [comment]
Hey @beshoo , over the last few releases, we've published a number of stability/usability fixes, so does this issue still happen with you on v0.0.14 of Beesy ?

**Comment by piyu-sh** [comment]
Since we haven't seen any activity on this for around half an year, closing it, please feel free to reopen in case needed.
