### ISSUE TITLE
Auto start the google meet recording

### ISSUE THREAD

**Issue by nomronCFP** [pi-ra/beesy-issue-tracker#41]
### Is there an existing request for this?

- [X] I have searched the existing issues

### Feature description

Would love to see a setting to auto start a the google meet recording when I join. Or even one to auto start the google meet recording when I'm the first to join, since google meet warns people joining if a recording is in progress.

Appreciate the local recording functionality, but having a google meet recording, which is accessible to all of those who attend is very helpful too.

**Comment by rahul-kurup** [comment]
Hey there @nomronCFP! Thanks for reaching out.

We're glad you like the extension! 
While auto-start recording would be great, browser limitations prevent us from implementing it. Since the recording is stored locally on your computer, we currently don't offer a way to share it over the internet.

However, we're developing some exciting new features that will be ready soon. You'll love them! 😊

**Comment by rahul-kurup** [comment]
I'm closing this for now. 
Alternatively you can use this Record reminder functionality: https://github.com/pi-ra/beesy-issue-tracker/issues/23
